# NumPy Cheat Sheet

<img src="NumPy_logo.svg">

In [1]:
import numpy as np

List yapısında her eleman için tip bilgisi saklanır, ama NumPy array'lerinde **fixed type** kullanıldığı ve type "array bazlı" olduğu için array içeriği tek tip olabilir, böylece işlem hızlılığı ve az veri kaplaması sağlanır. 

## shape

In [2]:
#shape metodunun output'u bir tuple'dır.

a = np.array([1,2,3,4,5])

a.shape

(5,)

## sıfırdan array oluşturma

In [3]:
#2d array oluşturma

np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
#sıfırlardan oluşan array

np.zeros(10).reshape(2,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
#birlerden oluşan array

np.ones(4).reshape(2,2)

array([[1., 1.],
       [1., 1.]])

In [6]:
#type belirleyerek array oluşturma

np.ones(4, dtype=int).reshape(2,2)

array([[1, 1],
       [1, 1]])

In [7]:
#3d array oluşturma (2 tane 3*4'lük matris)

np.ones(24).reshape(2,3,4)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [8]:
#0,1 harici bir sayıyla array oluşturma

np.full((3,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [9]:
#belirli bir sayı aralığı vererek array oluşturma(başlangıç,bitiş,eleman_sayısı), bitiş dahil.
#linspace fonksiyonunun arange'den farkı: linspace'te eleman sayısı, arange'de elemanların sayılarının artış değeri verilir.
#linspace:linear space

np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [10]:
#arange fonksiyonuyla(başlangıç,bitiş,aralık) vererek oluşturma, bitiş hariç

np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

In [11]:
#random fonksiyonuyla array oluşturma

np.random.randint(0,10,(3,3))

array([[5, 4, 0],
       [6, 5, 5],
       [2, 4, 1]])

In [12]:
#random fonksiyonuyla normal dağılımlı array oluşturma(ortalama,standart sapma,boyut)

np.random.normal(10,4,(3,4))

array([[18.13408192,  9.22570865,  8.40764087, 13.17476294],
       [11.57853054, 12.0231654 , 13.63512013, 11.58784192],
       [ 8.42601923,  0.57753877,  7.14930448,  3.45726889]])

## slicing

In [13]:
b = np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
#tek hücre seçimi

b[1,3]

8

In [15]:
#hücre aralığı seçimi

b[0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
#tüm satırlar ve bir sütun seçimi

b[:,3]

array([ 3,  8, 13])

In [17]:
#tüm satır ve sütunlar, belirlenen aralıkla (örnekte 2 atlayarak)

b[::2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

## concatenate

In [18]:
x = np.array([[1,2,3],
            [4,5,6]])
y = np.array([[5,6,7],
            [8,9,10]])

np.concatenate([x,y])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [19]:
#concatenate fonksiyonu axis parametresinin ön tanımlı değeri axis=0, yani satır bazlı birleştirme(alt alta). 
#sütun bazlısı (yan yana):

np.concatenate([x,y], axis = 1)

array([[ 1,  2,  3,  5,  6,  7],
       [ 4,  5,  6,  8,  9, 10]])

## split

In [20]:
c = np.arange(20).reshape(4,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [21]:
#satır bazında 1'e kadar,buradan 3'e kadar,buradan sona kadar ([] içerisinde verilen eleman sayısı+1 adet parçaya böler)

np.split(c,[1,3])

[array([[0, 1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]])]

In [22]:
#satır bazında bölme, vertical split

np.vsplit(c,[2,3])

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]])]

In [23]:
#sütun bazında bölme, horizontal split

np.hsplit(c,[1,3])

[array([[ 0],
        [ 5],
        [10],
        [15]]),
 array([[ 1,  2],
        [ 6,  7],
        [11, 12],
        [16, 17]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19]])]

## sort

In [24]:
#normal sort fonksiyonu gibi kalıcı değişiklik yapmaz. 1d array'lerde:

np.sort([5,9,3,6,4])

array([3, 4, 5, 6, 9])

In [25]:
#2d array'lerde satır bazında sıralama

u = np.array([[0,2,1],
          [3,6,8],
          [2,7,4]])
np.sort(u, axis =1)

array([[0, 1, 2],
       [3, 6, 8],
       [2, 4, 7]])

In [26]:
#2d array'lerde sütun bazında sıralama

np.sort(u, axis =0)

array([[0, 2, 1],
       [2, 6, 4],
       [3, 7, 8]])

## copy

In [27]:
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
#bir matrisin alt kümesini alıp onunla işlem yapıldığında bu matrisi de etkiler, bu nedenle çalışmaya başlamadann önce copy 
#metodu kullanılarak matrisin bir kopyası alınarak çalışma bunun üzerinde yapılır.

subset = c[:3,:2].copy()
subset

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

## ndim

In [29]:
#array'in kaç boyutlu olduğunu gösterir, number of dimension

d = np.array([8,9,10])

d.ndim

1

In [30]:
c.ndim

2

## size

In [31]:
#eleman sayısını gösterir

c.size

20

## genfromtxt

* csv, txt dosyasını np.array'e dönüştürür, csv dosyasının delimiter'ını (yani her bir gözlemdeki değerleri ayıran karakteri) parametre olarak verebiliriz,
* eğer başlık varsa bu satırı es geçebiliriz (kaç satırı es geçeceğimizi parametre olarak verebiliriz)
* fixed type tutabildiği için integer ya da float tipinin dışındaki elemanları NaN (not a number) olarak saklar
* dosya yolunu verirken, Python çalışma dosyasına göre konumunu belirtmemiz gerekli

np.genfromtxt("dosya_yolu", delimiter=",", skip_header=1,dtype =int)

## boolean array | mask indexing

In [32]:
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
#belirli bir koşulu sağlayıp sağlamadığını görme

c < 12

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False, False, False],
       [False, False, False, False, False]])

In [34]:
#belirli bir koşulu sağlayan elemanları bir array içerisinde görme

c[c<12]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
#belirli bir koşulu sağlayan elemanlara slicing uygulama

c[c<12][:3]

array([0, 1, 2])

In [36]:
#belirli bir koşulu sağlayan elemanlara yeni değer atama, c array'inde 12'den küçük olan değerlere 100 eklendi:

c[c < 12] += 100
c

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

In [37]:
d = np.arange(10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
#bir koşula bağlı olarak başka bir index'teki elemana değer atama 
#(d[5]'teki değer 5'e eşitse, d[2]'ye 99 değerini ata)

d[d[5] == 5, 2] = 99
d

array([ 0,  1, 99,  3,  4,  5,  6,  7,  8,  9])

## where (if statement)

In [39]:
c

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

In [40]:
#eğer array'deki değer 12'den büyükse bu değeri 100 olarak ata, büyük değilse 0 olarak ata
#boolean | mask indexing'den farklı olarak koşulu sağlamadığı durum için de bir atama yapılıyor, if/else mantığıyla

arr = np.where(c > 12, 100, 0)
arr

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100,   0, 100, 100],
       [100, 100, 100, 100, 100]])

## fancy indexing

In [41]:
#bir array içerisinde birden fazla elemana (belirli bir sırayı takip etmeyen)ulaşmak için list olarak index'lerini veriyoruz
#1d array'deki örneği (1. 3. ve 5. indexlerdeki değerleri bir array'de topladı)

e = np.array([0,1,2,5,6,7])
liste = [1,3,5]
e[liste]

array([1, 5, 7])

In [42]:
#2d array'deki örneği (list içerisinde index veriliyor, slice gibi "-e kadar" mantığı yok)

f = np.array([[0,1,2],
              [3,4,5],
              [6,7,8]])
satir = np.array([0,1])
sutun = np.array([1,2])
f[satir,sutun]

array([1, 5])

In [43]:
#liste yerine bir sayı da verilebilir, index:1 satırında index:1'den 2'ye kadar elemanları getir:

f[1,[1,2]]

array([4, 5])

## ufunc (universal functions)

In [44]:
#ndarray'ler üzerinde hücre hücre işlem yapan fonksiyonlardır, örneğin basit matematiksel işlemlerin arkaplanında çalışanlar


f = np.array([3,4,5,6,7,8])
np.divide(f,2)   #f / 2 ile aynıdır

array([1.5, 2. , 2.5, 3. , 3.5, 4. ])

## iki bilinmeyenli denklem çözümü

7x1  + 3x2 = 70  
    x1 + 4x2 = 35

In [46]:
#ilk bilinmeyenin ve ikinci bilinmeyenin katsayıları bir ndarray olarak veriliyor, 
#başka bir array'de denklemin diğer tarafındaki eşitlikler veriliyor.
#output sırasıyla x1 ve x2'nin değerleri
#linalg: linear algebra

g = np.array([[7,1], [3,4]])
h = np.array([70,35])
i = np.linalg.solve(g,h)
i

array([9.8, 1.4])